version: '3.8'

services:
  stt-server:
    image: ghcr.io/bmv234/stt-api-server:latest
    # Uncomment the next line to build locally instead of pulling from GHCR
    # build: .
    container_name: stt-server
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "--insecure", "https://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
